### ISSUE TITLE
error: ‘__restrict__’ qualifiers cannot be applied to ‘void’

### ISSUE THREAD

**Issue by nemequ** [coderforlife/ms-compress#16]
https://travis-ci.org/quixdb/squash/builds/64494774

Seems to be restricted to GCC < 4.9… that build is with 4.8, but 4.9 on Fedora 21 and 5.1 on Fedora 22 work.  clang also fails on 3.4 there, but…

I'm also seeing an error with clang 3.5 (on an Ubuntu 14.10 VM) about "no matching function for call to 'free'"… "note: candidate function not viable: no known conversion from 'const_rest_bytes *' (aka 'const unsigned char *restrict *') to 'void *' for 1st argument"…

**Comment by coderforlife** [comment]
I need some clarifications. Please tell me if the following are correct.
 * Works on GCC 4.9 and 5.1 but not GCC 4.8 (on my side MinGW/GCC 4.9.2 works in Windows, I did not test in Linux)
 * Does not work with Clang 3.4
 * Both of the above result in the error "error: ‘__restrict__’ qualifiers cannot be applied to ‘void’"
 * In Clang 3.5 a different error message is given: "note: candidate function not viable: no known conversion from 'const_rest_bytes *' (aka 'const unsigned char *restrict *') to 'void *' for 1st argument"

I will go and start investigating this (I have easy access to GCC 4.9.2 and Clang 3.5 on Fedora 21 and GCC 4.8.3 on CentOS 7). In the mean time, if you go back just one commit nothing using restrict there (and it turned out not to help too much anyways). It could easily be removed.

[Side note: have you tried the unaligned access build configuration? On my normal build machine (Windows) the various GCC tools like ubsan are not available]

**Comment by coderforlife** [comment]
The GCC issue is confirmed to be fixed in v4.9.2: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60872

The main problem seems that even though I am not using void* RESTRICT pointers anywhere that GCC pre-4.9.2 (and apparently Clang) try to make them implicitly with functions like free although they shouldn't. According to bug report, even using an explicit cast to void* doesn't help in GCC pre-4.92.

**Comment by nemequ** [comment]
Basically all those points are correct.  The error message is *slightly* different in clang 3.4 ("error: ‘__restrict__’ qualifiers cannot be applied to ‘void’").  In the link I posted, if you click on one of the two items under "Build Jobs" it will bring up the full build log, including the error messages.  The clang one is clang 3.4, the gcc one is gcc 4.8.

> [Side note: have you tried the unaligned access build configuration? On my normal build machine (Windows) the various GCC tools like ubsan are not available]

I haven't yet, but I'll do so over the weekend.

**Comment by coderforlife** [comment]
Fixed the problem in a179b8d46c76048872470ba449f672aa064131e6 with GCC pre-4.9.2 by removing the only pointer that was restricted and passed to a builtin function that took void*.

**Comment by nemequ** [comment]
Oops, I take that back—they're the same.  github treating it as markdown thew me a bit.

> Fixed the problem in a179b8d with GCC pre-4.9.2 by removing the only pointer that was restricted and passed to a builtin function that took void*.

Okay, I'll push an update to squash to kick off another travis build.

**Comment by coderforlife** [comment]
I just checked clang 3.5 and no errors there either. The last question is with clang 3.4 which I don't have easy access to.

**Comment by nemequ** [comment]
Works from travis with gcc 4.8 and clang 3.4: https://travis-ci.org/quixdb/squash/builds/64512295

**Comment by coderforlife** [comment]
Great!
